### ISSUE TITLE
Paragon Cap Stats to 255

### ISSUE THREAD

**Issue by Synz75** [iThorgrim-Hub/lua-aio-parangon#2]
![Screenshot_2](https://user-images.githubusercontent.com/11411617/109206522-f463eb00-7775-11eb-8d45-4098f3d54037.png)
![Screenshot_3](https://user-images.githubusercontent.com/11411617/109206562-02197080-7776-11eb-85e1-06567b150e5d.png)

**Comment by iThorgrim-Hub** [comment]
It's now fix #https://github.com/iThorgrim-Hub/lua-aio-parangon/commit/d8a0b83b9d152caa3d8a76840362b728da862575
