### ISSUE TITLE
Parangon not affecting in game stats.

### ISSUE THREAD

**Issue by FatGrandpa007** [iThorgrim-Hub/lua-aio-parangon#3]
So I just installed the Parangon aio system from scratch, completely default.
But anything we put into the system doesn't actually effect character stats at all.
It doesn't change anything under "C" character info.
Nor does it add to health or anything.
Not sure if this is a common issue or not but I can't seem to get it working at all.

And also, if I put in say 100 points in stamina, and I got 0 points left to use.
If I relog I got another 100 points over again, and the points I used in stamina are still applied in the tab.
So if I spend the new 100 points as well and relog I then have 200 points and previous points used are still applied.

**Comment by iThorgrim-Hub** [comment]
It's now fix #https://github.com/iThorgrim-Hub/lua-aio-parangon/commit/d8a0b83b9d152caa3d8a76840362b728da862575
