### ISSUE TITLE
parangon-client.lua Error 

### ISSUE THREAD

**Issue by Anhedonie-Shanrai** [iThorgrim-Hub/lua-aio-parangon#4]
Hey, just installed AIO + your parangon script, unfortunately I get an error: 

Error: [string "parangon-client.lua"]:23: attempt to concatenate local 'r' (a nil value) 

Can't seem to fix it. AIO is up and running. 

![image](https://user-images.githubusercontent.com/82074951/115154509-776d3780-a07b-11eb-8ce9-e717b0e353de.png)

**Comment by iThorgrim-Hub** [comment]
You have AIO on Server and client ?

**Comment by DevCores** [comment]
Confirm. There is this error.

**Comment by DevCores** [comment]
> You have AIO on Server and client ?

Confirm. There is this error.
Everything is added according to the instructions, but an error occurs in line 23 of AIO

**Comment by iThorgrim-Hub** [comment]
Thanks ꧁ DeVvv ꧂ for help.

Error Fix !

**Comment by Anhedonie-Shanrai** [comment]
Such a simple fix! Amazing, thank you very much, works like intended now!

**Comment by Ruok-Capsule** [comment]
Hi , i've the same problem , how can i fix this
